import type { Pet } from "./types";

import imgPluto from "../../imports/Catalog/7abaafcc2a09d50e0fc877db77c9c704cd360ae6.png";
import imgJasper from "../../imports/Manada/05315c921ffb0646b298e09ecd7293761ebbf584.png";
import imgMain from "../../imports/DetalleDeMascotaLeoPet/b5e67b3823fbd4287dcd8b82dc791a0d64b1d4a9.png";
import imgFood from "../../imports/DetalleDeMascotaLeoPet/9ec279e8e0b77d8a1cef5b76d12950fe70e8b841.png";
import imgPlay from "../../imports/DetalleDeMascotaLeoPet/bd95c8085784a9dd890c235868f306b717608099.png";

export const MOCK_PETS: Pet[] = [
  {
    id: "1",
    name: "Pluto",
    breed: "Beagle Mix",
    age: "3 años",
    foundation: "Refugio Almas Peludas",
    foundationId: "f1",
    status: "Saludable",
    description: "Pluto fue encontrado vagando cerca del centro de la ciudad.",
    story: "Pluto fue encontrado vagando cerca del centro de la ciudad, cansado y con hambre pero mantiendo siempre la alegría. Su espíritu dócil y resiliente lo ha convertido en un favorito en la fundación. Como mezcla de Beagle, Pluto es curioso y enérgico por naturaleza. Le encantan los paseos al aire libre y un rincón tranquilo para descansar después de jugar. Se lleva de maravilla con niños y otras mascotas. Tu apadrinamiento le proporcionará a Pluto alimentación especializada y terapia física para una condición leve de cadera.",
    healthStatus: [
      { title: "Vacunación Completa", desc: "Al día con todas sus vacunas esenciales." },
      { title: "Desparasitación", desc: "Tratamiento preventivo continuo." },
      { title: "Condición leve", desc: "Requiere suplemento articular preventivo." },
      { title: "Esterilizado", desc: "Procedimiento realizado con éxito." },
    ],
    image: imgMain,
    galleryImages: [imgFood, imgPlay],
    location: "Guayaquil",
    sex: "Macho",
    weight: "9 Kg",
    category: "perro",
  },
  {
    id: "2",
    name: "Luna",
    breed: "Siamés Mix",
    age: "1 año",
    foundation: "Refugio Amigos Felinos",
    foundationId: "f2",
    status: "Saludable",
    description: "Luna es una gata curiosa y cariñosa que ama los mimos.",
    story: "Luna fue rescatada de la calle cuando era apenas un cachorro. Desde entonces, ha mostrado una personalidad juguetona y afectuosa. Le encanta trepar a lugares altos y perseguir juguetes. Es perfecta para familias con niños.",
    healthStatus: [
      { title: "Vacunación Completa", desc: "Al día con sus vacunas." },
      { title: "Esterilizada", desc: "Procedimiento completado." },
      { title: "Saludable", desc: "Sin condiciones conocidas." },
    ],
    image: imgJasper,
    galleryImages: [imgFood],
    location: "Quito",
    sex: "Hembra",
    weight: "3.5 Kg",
    category: "gato",
  },
  {
    id: "3",
    name: "Toby",
    breed: "Labrador Mix",
    age: "2 años",
    foundation: "Huellitas Sanas",
    foundationId: "f3",
    status: "En tratamiento",
    description: "Toby es un perro enérgico que necesita tratamiento ortopédico.",
    story: "Toby fue rescatado con una condición en su pata trasera. Tras meses de rehabilitación, está listo para encontrar un padrino que ayude a cubrir sus tratamientos restantes. Es extremadamente leal y cariñoso.",
    healthStatus: [
      { title: "Vacunación Completa", desc: "Al día con todas sus vacunas." },
      { title: "Tratamiento activo", desc: "Rehabilitación ortopédica en curso." },
      { title: "Esterilizado", desc: "Procedimiento completado." },
    ],
    image: imgPluto,
    galleryImages: [imgFood, imgPlay],
    location: "Cuenca",
    sex: "Macho",
    weight: "22 Kg",
    category: "perro",
  },
  {
    id: "4",
    name: "Michi",
    breed: "Mestizo",
    age: "4 meses",
    foundation: "Refugio Amigos Felinos",
    foundationId: "f2",
    status: "Saludable",
    description: "Michi es un cachorro juguetón lleno de energía.",
    story: "Michi llegó al refugio siendo muy pequeño. Ahora está creciendo fuerte y buscando un hogar lleno de amor. Le encanta jugar con pelotas y rascarse detrás de las orejas.",
    healthStatus: [
      { title: "Vacunas pendientes", desc: "Necesita completar su esquema de vacunación." },
      { title: "Desparasitado", desc: "Tratamiento preventivo al día." },
    ],
    image: imgJasper,
    galleryImages: [imgPlay],
    location: "Guayaquil",
    sex: "Macho",
    weight: "1.2 Kg",
    category: "gato",
  },
  {
    id: "5",
    name: "Rex",
    breed: "Pastor Alemán Mix",
    age: "5 años",
    foundation: "Refugio Almas Peludas",
    foundationId: "f1",
    status: "Saludable",
    description: "Rex es un perro leal y protector, ideal para familias grandes.",
    story: "Rex fue abandonado por su familia anterior. A pesar de ello, sigue siendo el perro más amoroso del refugio. Es perfecto para familias con espacio y amor para dar.",
    healthStatus: [
      { title: "Vacunación Completa", desc: "Al día con todas sus vacunas." },
      { title: "Esterilizado", desc: "Procedimiento completado." },
      { title: "Saludable", desc: "Sin condiciones conocidas." },
    ],
    image: imgMain,
    galleryImages: [imgFood, imgPlay],
    location: "Ambato",
    sex: "Macho",
    weight: "28 Kg",
    category: "perro",
  },
  {
    id: "6",
    name: "Nina",
    breed: "Persa Mix",
    age: "2 años",
    foundation: "Huellitas Sanas",
    foundationId: "f3",
    status: "Saludable",
    description: "Nina es una gata tranquila que disfruta de la calma.",
    story: "Nina fue encontrada cerca de un parque, muy asustada. Con paciencia y cariño, se ha convertido en una compañera dulce y serena. Le gusta estar cerca de personas y dormir en lugares cómodos.",
    healthStatus: [
      { title: "Vacunación Completa", desc: "Al día con sus vacunas." },
      { title: "Esterilizada", desc: "Procedimiento completado." },
    ],
    image: imgFood,
    galleryImages: [imgJasper],
    location: "Loja",
    sex: "Hembra",
    weight: "4 Kg",
    category: "gato",
  },
];

export const MOCK_EVIDENCE = [
  {
    id: "ev-1",
    petId: "1",
    petName: "Pluto",
    foundationName: "Refugio Almas Peludas",
    type: "photo" as const,
    title: "Pluto disfrutando de su almuerzo especial",
    description: "Pluto comió con mucho apetito hoy. Su alimentación especializada está dando excelentes resultados.",
    imageUrl: imgFood,
    date: "2026-07-20",
  },
  {
    id: "ev-2",
    petId: "1",
    petName: "Pluto",
    foundationName: "Refugio Almas Peludas",
    type: "photo" as const,
    title: "Sesión de juego en el patio",
    description: "Pluto jugó durante 30 minutos sin mostrar signos de dolor articular. La terapia está funcionando.",
    imageUrl: imgPlay,
    date: "2026-07-18",
  },
  {
    id: "ev-3",
    petId: "2",
    petName: "Luna",
    foundationName: "Refugio Amigos Felinos",
    type: "video" as const,
    title: "Luna explorando su nuevo rincón",
    description: "Luna descubrió un nuevo árbol para gatos y no para de trepar. ¡Muy feliz!",
    imageUrl: imgJasper,
    date: "2026-07-19",
  },
  {
    id: "ev-4",
    petId: "3",
    petName: "Toby",
    foundationName: "Huellitas Sanas",
    type: "photo" as const,
    title: "Toby en su sesión de rehabilitación",
    description: "Toby completó su terapia física semanal. El veterinario reporta mejoras significativas en su movilidad.",
    imageUrl: imgPlay,
    date: "2026-07-17",
  },
];
